server:
  home_dir: "~/.gears"
logging:
  default:
    console_level: info
opentelemetry:
  resource:
    service_name: "gears"
    attributes:
      project_name: "hello_world"
  exporter:
    kind: otlp_grpc
  tracing:
    enabled: false
  metrics:
    enabled: false
gears:
  hello-world:
    config:
      interval: 1
