server:
  home_dir: "~/.cyberfabric"
logging:
  default:
    console_level: info
tracing:
  enabled: false
  metrics:
    enabled: false
    exporter:
      kind: otlp_grpc
modules:
  hello-world:
    config:
      interval: 1
    metadata:
      package: "hello-world"
      version: "0.0.1"
